swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: jAvascript:prompt('https://google.com')
info:
  version: "0.0.1"
  title: Example Title
  description: Please Authorize!111222 <object data="pic_trulli.jpg">
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
