swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: jAvascript:prompt('https://google.com')
info:
  version: "0.0.1"
  title: Example Title
  description: Please Authorize!12 <img src=x onerror=alert(1) /><b>aaa</b><if<iframe>rame src=x></iframe>
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
